### ISSUE TITLE
Lunar not launching with javaagents.

### ISSUE THREAD

**Issue by NGB-Was-Taken** [Nilsen84/lunar-client-agents#17]
So, I downloaded the JavaAgents CrackedAccounts, LunarEnable and NoPinnedServers to be exact but lunar doesn't launch. I'm not using lunar client qt because it doesn't support 32bit.
Here is the command I am using to launch lunar 
```
C:\Users\Lenovo\.lunarclient\jre\1.8\zulu16.30.15-ca-jre16.0.1-win_i686\bin\java.exe --add-modules jdk.naming.dns --add-exports jdk.naming.dns/com.sun.jndi.dns=java.naming -Djna.boot.library.path=C:\Users\Lenovo\.lunarclient\offline\1.8\natives --add-opens java.base/java.io=ALL-UNNAMED -Xms512M -Xmx712M -Xmn256M -XX:+UnlockExperimentalVMOptions -XX:+UseG1GC -XX:G1NewSizePercent=20 -XX:G1ReservePercent=20 -XX:MaxGCPauseMillis=50 -XX:G1HeapRegionSize=32M -Djava.library.path=C:\Users\Lenovo\.lunarclient\offline\1.8\natives -XX:+DisableAttachMechanism -cp C:\Users\Lenovo\.lunarclient\offline\1.8\lunar-assets-prod-1-optifine.jar;C:\Users\Lenovo\.lunarclient\offline\1.8\lunar-assets-prod-2-optifine.jar;C:\Users\Lenovo\.lunarclient\offline\1.8\lunar-assets-prod-3-optifine.jar;C:\Users\Lenovo\.lunarclient\offline\1.8\lunar-libs.jar;C:\Users\Lenovo\.lunarclient\offline\1.8\lunar-prod-optifine.jar;C:\Users\Lenovo\.lunarclient\offline\1.8\OptiFine.jar;C:\Users\Lenovo\.lunarclient\offline\1.8\vpatcher-prod.jar -javaagent:C:\Users\Lenovo\Desktop\modules\lcagents\CrackedAccount.jar=_NGB_ -javaagent:C:\Users\Lenovo\Desktop\modules\lcagents\LunarEnable.jar -javaagent:C:\Users\Lenovo\Desktop\modules\lcagents\NoPinnedServers.jar com.moonsworth.lunar.patcher.LunarMain --version 1.8 --accessToken 0 --assetIndex 1.8 --userProperties {} --gameDir C:\Users\Lenovo\AppData\Roaming\.minecraft --launcherVersion 2.10.0 --width 854 --height 480 --texturesDir C:\Users\Lenovo\.lunarclient\textures --assetsDir C:\Users\Lenovo\AppData\Roaming\.minecraft\assets
```

LC launched like normal if I remove the agents but I get this error when I put them in.
```
Exception in thread "main" java.lang.NoClassDefFoundError: org/objectweb/asm/tree/ClassNode
        at java.base/java.lang.Class.getDeclaredMethods0(Native Method)
        at java.base/java.lang.Class.privateGetDeclaredMethods(Unknown Source)
        at java.base/java.lang.Class.getDeclaredMethod(Unknown Source)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndStartAgent(Unknown Source)
        at java.instrument/sun.instrument.InstrumentationImpl.loadClassAndCallPremain(Unknown Source)
Caused by: java.lang.ClassNotFoundException: org.objectweb.asm.tree.ClassNode
        at java.base/jdk.internal.loader.BuiltinClassLoader.loadClass(Unknown Source)
        at java.base/jdk.internal.loader.ClassLoaders$AppClassLoader.loadClass(Unknown Source)
        at java.base/java.lang.ClassLoader.loadClass(Unknown Source)
        ... 5 more
*** java.lang.instrument ASSERTION FAILED ***: "result" with message agent load/premain call failed at c:\jenkins\workspace\zulu16-build-win32\zulu-src.git\src\java.instrument\share\native\libinstrument\JPLISAgent.c line: 422
FATAL ERROR in native method: processing of -javaagent failed, processJavaStart failed
```

**Comment by Nilsen84** [comment]
You need to add asm-tree:9.2 and asm:9.2 to the class path. They can be found in the libs directory of an lcqt release or on maven.
